apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - priority-classes.yaml

commonLabels:
  app.kubernetes.io/name: priority-classes
  app.kubernetes.io/component: scheduling
  app.kubernetes.io/managed-by: kustomize