apiVersion: v1
kind: ResourceQuota
metadata:
  name: lakeshirts-prod-quota
  namespace: lakeshirts-prod
spec:
  hard:
    # Compute resources
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    
    # Storage resources
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # Object counts
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
    replicationcontrollers: "10"
    
    # Load balancers
    services.loadbalancers: "5"
    services.nodeports: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lakeshirts-dev-quota
  namespace: lakeshirts-dev
spec:
  hard:
    # Compute resources
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    
    # Storage resources
    requests.storage: 50Gi
    persistentvolumeclaims: "5"
    
    # Object counts
    pods: "25"
    services: "10"
    secrets: "10"
    configmaps: "10"
    replicationcontrollers: "5"
    
    # Load balancers
    services.loadbalancers: "2"
    services.nodeports: "5"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: lakeshirts-staging-quota
  namespace: lakeshirts-staging
spec:
  hard:
    # Compute resources
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    
    # Storage resources  
    requests.storage: 75Gi
    persistentvolumeclaims: "8"
    
    # Object counts
    pods: "40"
    services: "15"
    secrets: "15"
    configmaps: "15"
    replicationcontrollers: "8"
    
    # Load balancers
    services.loadbalancers: "3"
    services.nodeports: "8"