apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - daemonset.yaml

commonLabels:
  app.kubernetes.io/name: node-problem-detector
  app.kubernetes.io/component: monitoring
  app.kubernetes.io/managed-by: kustomize