apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.9.12
    helm:
      values: |
        loki:
          config:
            table_manager:
              retention_deletes_enabled: true
              retention_period: 7d
          persistence:
            enabled: true
            size: 20Gi
            storageClassName: local-path

        promtail:
          enabled: true
          config:
            clients:
              - url: http://logging-loki:3100/loki/api/v1/push
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
