apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-configs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4gd-Lakeshirts/cluster-infra
    targetRevision: HEAD
    path: infrastructure/ingress-controller/overlays/prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
