apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4gd-Lakeshirts/cluster-infra
    targetRevision: HEAD
    path: applications/microservices-demo/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
