apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 61.9.0  # Stable version known to work well
    helm:
      skipCrds: false  # Let it manage CRDs
      values: |
        # Global settings
        commonLabels:
          app.kubernetes.io/part-of: monitoring-stack
        
        # Prometheus Configuration
        prometheus:
          enabled: true
          prometheusSpec:
            # Image settings
            image:
              registry: quay.io
              repository: prometheus/prometheus
              tag: v2.53.1  # Stable tag
              pullPolicy: IfNotPresent
            
            # Basic settings
            retention: 15d
            retentionSize: 15GB
            replicas: 1
            shards: 1
            
            # Resource limits - conservative but adequate
            resources:
              requests:
                memory: "2Gi"
                cpu: "1000m"
              limits:
                memory: "4Gi"
                cpu: "2000m"
            
            # Storage configuration
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
            
            # Disable problematic features
            enableOTLPReceiver: false
            enableRemoteWriteReceiver: false
            
            # Service monitor settings
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            
          # Service configuration
          service:
            type: NodePort
            nodePort: 30090
            port: 9090
        
        # Alertmanager Configuration
        alertmanager:
          enabled: true
          alertmanagerSpec:
            replicas: 1
            retention: 120h
            
            # Resource limits
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"
            
            # Storage
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: local-path
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 2Gi
          
          # Service configuration
          service:
            type: NodePort
            nodePort: 30093
            port: 9093
        
        # Grafana Configuration
        grafana:
          enabled: true
          adminPassword: "admin123"
          
          # Resource limits
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          
          # Storage
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: local-path
            accessModes: ["ReadWriteOnce"]
          
          # Service
          service:
            type: NodePort
            nodePort: 30080
            port: 80
          
          # Basic plugins
          plugins:
            - grafana-piechart-panel
          
          # Default dashboards
          defaultDashboardsEnabled: true
          
          # Grafana config
          grafana.ini:
            analytics:
              check_for_updates: false
            log:
              mode: console
            paths:
              data: /var/lib/grafana/
              logs: /var/log/grafana
              plugins: /var/lib/grafana/plugins
              provisioning: /etc/grafana/provisioning
        
        # Prometheus Node Exporter
        prometheus-node-exporter:
          enabled: true
          
          # Resource limits
          resources:
            requests:
              memory: "30Mi"
              cpu: "100m"
            limits:
              memory: "50Mi"
              cpu: "200m"
          
          # Configuration
          hostRootFsMount:
            enabled: true
            mountPropagation: HostToContainer
          
          extraArgs:
            - --path.rootfs=/host/root
            - --web.listen-address=[$(HOST_IP)]:9100
          
          service:
            port: 9100
            targetPort: 9100
        
        # Kube State Metrics
        kube-state-metrics:
          enabled: true
          
          # Resource limits
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          
          prometheus:
            monitor:
              enabled: true
        
        # Prometheus Operator - CRITICAL SECTION
        prometheusOperator:
          enabled: true
          
          # Resource limits - key to solving your issue
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          
          # Config reloader resources
          configReloaderResources:
            requests:
              memory: "25Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "50m"
          
          # Prometheus config reloader resources
          prometheusConfigReloaderResources:
            requests:
              memory: "25Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "50m"
          
          # Log level
          logLevel: info
          logFormat: logfmt
          
          # Admission webhooks - can cause issues, disable
          admissionWebhooks:
            enabled: false
          
          # TLS config
          tls:
            enabled: false
          
          # Service account
          serviceAccount:
            create: true
        
        # Disable components that can cause issues
        kubeApiServer:
          enabled: true
        
        kubelet:
          enabled: true
        
        kubeControllerManager:
          enabled: false  # Often not accessible in managed clusters
        
        coreDns:
          enabled: true
        
        kubeEtcd:
          enabled: false  # Often not accessible in managed clusters
        
        kubeScheduler:
          enabled: false  # Often not accessible in managed clusters
        
        kubeProxy:
          enabled: false  # Can cause networking issues
        
        # Node selection and tolerations
        nodeExporter:
          jobLabel: node-exporter
        
        # Global monitoring settings
        global:
          rbac:
            create: true
            pspEnabled: false
