apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.1
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true

        server:
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              # THIS IS THE CRITICAL PART - Actual Raft storage configuration
              config: |
                ui = true
                
                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                }
                
                storage "raft" {
                  path = "/vault/data"
                  
                  retry_join {
                    leader_api_addr = "http://vault-0.vault-internal:8200"
                  }
                  
                  retry_join {
                    leader_api_addr = "http://vault-1.vault-internal:8200"
                  }
                  
                  retry_join {
                    leader_api_addr = "http://vault-2.vault-internal:8200"
                  }
                }
                
                service_registration "kubernetes" {}
                
                disable_mlock = true

          dataStorage:
            enabled: true
            storageClass: local-path
            size: 8Gi

          volumePermissions:
            enabled: true
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

          service:
            type: LoadBalancer 
            port: 8200
            annotations:
              metallb.universe.tf/loadBalancerIPs: "192.168.101.232"
          # Disable active/standby services to avoid IP conflicts
          activeService:
            enabled: false
          standbyService:
            enabled: false

          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: haproxy
              haproxy.org/backend-protocol: "http"
              haproxy.org/check: "true"
              haproxy.org/check-http: "/v1/sys/health"
            ingressClassName: haproxy

            hosts:
              - host: vault.local
                paths: 
                  - /

            pathType: Prefix

          # Pod anti-affinity to spread across healthy nodes
          affinity: |
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: vault
                      app.kubernetes.io/instance: "vault"
                      component: server
                  topologyKey: kubernetes.io/hostname

        ui:
          enabled: true
        injector:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
