apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.1
    helm:
      values: |
        server:
          ha:
            enabled: true
            replicas: 3
          raft:
            enabled: true
          dataStorage:
            enabled: true
            storageClass: local-path
            size: 8Gi

          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

          service:
            type: ClusterIP
            port: 8200

          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: haproxy
              haproxy.org/backend-protocol: "http"
            hosts:
              - host: vault.local
                paths: 
                  - /

        ui:
          enabled: true

        injector:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
