apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.30.1
    helm:
      values: |
        server:
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
          dataStorage:
            enabled: true
            storageClass: local-path
            size: 8Gi
          service:
            type: ClusterIP
            port: 8200
          # Ingress configuration at server level
          ingress:
            enabled: true
            ingressClassName: haproxy
            annotations:
              haproxy-ingress.github.io/rewrite-target: /
              haproxy-ingress.github.io/backend-protocol: "http"              
            hosts:
              - host: vault.192.168.101.191.nip.io
                paths:
                  - /
            pathType: Prefix

        ui:
          enabled: true
          serviceType: ClusterIP
        injector:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
