apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.kasten.io/
    chart: k10
    targetRevision: 7.5.1
    helm:
      values: |
        eula:
          accept: true
          company: "Lakeshirts"
          email: "suyash@4gd.ai"
        auth:
          tokenAuth:
            enabled: true
        global:
          persistence:
            storageClass: local-path
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
