global:
  enabled: true
  tlsDisable: true

server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "http://vault-0.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-1.vault-internal:8200"
          }
          retry_join {
            leader_api_addr = "http://vault-2.vault-internal:8200"
          }
        }

        service_registration "kubernetes" {}
        disable_mlock = true

  dataStorage:
    enabled: true
    storageClass: azurefile-csi   # ✅ DR storage class
    size: 8Gi

  volumePermissions:
    enabled: true

  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  service:
    type: ClusterIP   # ✅ don’t expose with LB
    port: 8200

  ingress:
    enabled: true
    ingressClassName: haproxy
    annotations:
      haproxy.org/backend-protocol: "http"
      haproxy.org/check: "true"
      haproxy.org/check-http: "/v1/sys/health"
    hosts:
      - host: vault.20-120-45-10.nip.io
        paths:
          - /
    tls:
      - hosts:
          - vault.20-120-45-10.nip.io
        secretName: vault-dr-tls

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: vault
              app.kubernetes.io/instance: vault
              component: server
          topologyKey: kubernetes.io/hostname

ui:
  enabled: true

injector:
  enabled: false
