apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasten-io
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Opensys-Lakeshirts/cluster-infra
    targetRevision: dev
    path: infrastructure/kasten-io/overlays/dr
    helm:
      releaseName: kasten-io
      valueFiles:
        - values-dr.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
