apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://haproxytech.github.io/helm-charts
    chart: kubernetes-ingress
    targetRevision: 1.44.0
    helm:
      values: |
        controller:
          ingressClassResource:
            default: true
            name: haproxy
          ingressClass: haproxy
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
            labels:
              app.kubernetes.io/name: kubernetes-ingress
              app.kubernetes.io/instance: ingress-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
