apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.1
    helm:
      skipCrds: true
      values: |
        installCRDs: false
        ingressShim:
          defaultIssuerName: letsencrypt-prod
          defaultIssuerKind: ClusterIssuer
          defaultIssuerGroup: cert-manager.io

        # Force correct image arch
        image:
          repository: quay.io/jetstack/cert-manager-controller
          tag: v1.18.1
          # optional but recommended
          pullPolicy: IfNotPresent

        cainjector:
          image:
            repository: quay.io/jetstack/cert-manager-cainjector
            tag: v1.18.1

        webhook:
          image:
            repository: quay.io/jetstack/cert-manager-webhook
            tag: v1.18.1
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
