apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/cert-manager/cert-manager/releases/download/v1.18.1/cert-manager.crds.yaml
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc   # <--- required
    namespace: cert-manager                  # even though CRDs are cluster-scoped
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
