apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-infra-dr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/4gd-Lakeshirts/cluster-infra
    targetRevision: dev   # or main once merged
    path: clusters/dr     # <-- IMPORTANT: folder, not file
    directory:
      recurse: true       # <-- tells ArgoCD to render kustomize, not apply as CRD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
