apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../infrastructure/argocd/overlays/dr
  - ../../infrastructure/cert-manager/overlays/dr
  - ../../infrastructure/kyverno/overlays/dr
  # - ../../infrastructure/logging/overlays/dr
  - ../../infrastructure/monitoring/overlays/dr
  - ../../infrastructure/vault/overlays/dr
  - ../../infrastructure/kasten-io/overlays/dr
  - ../../infrastructure/metrics-server/overlays/dr
  - ../../infrastructure/pod-security/overlays/dr
  - ../../infrastructure/priority-classes/overlays/dr
  - ../../infrastructure/node-problem-detector/overlays/dr
  - ../../infrastructure/resource-quotas/overlays/dr
  - ../../infrastructure/ingress-controller/overlays/dr
  - ../../infrastructure/argo-rollouts/overlays/dr
